### ISSUE TITLE
rgn_all_codes.csv first field contains whitespace

### ISSUE THREAD

**Issue by michaelwood** [drkane/geo-lookups#2]
The first field in rgn_all_codes.csv  contains ﻿ U+FEFF ZERO WIDTH NO-BREAK SPACE, decimal: 65279, HTML: No visual representation, UTF-8: 0xEF 0xBB 0xBF, block: Arabic Presentation Forms-B

`\ufeffRGNCD`

This is reproducible via  

```python
In [1]: a = open("rgn_all_codes.csv", "r")                                                                                   
In [3]: a.read()                                                                                                             
Out[3]: '\ufeffRGNCD,RGNNM,CTRYCD,CTRYNM,EWCD,EWNM,GBCD,GBNM,UKCD,UKNM....
```

This causes https://github.com/ThreeSixtyGiving/datastore/issues/71 not to be able to lookup the area field name.

**Comment by drkane** [comment]
Thanks - merged the PR.

NB if I remember I try to open csv with `encoding='utf-8-sig'` which means it ignores the BOM at the start. I think Excel saves csv files with the BOM at the start.
